libtpp_sources = files(
  'auth_server.cpp',
  'automod.cpp',
  'channel_points.cpp',
  'chat_notification.cpp',
  'conduit.cpp',
  'consumer.cpp',
  'dns.cpp',
  'emote.cpp',
  'eventsub_events.cpp',
  'eventsub_transport.cpp',
  'events/automod_message_hold.cpp',
  'events/automod_message_update.cpp',
  'events/automod_settings_update.cpp',
  'events/automod_terms_update.cpp',
  'events/channel_ad_break_begin.cpp',
  'events/channel_ban.cpp',
  'events/channel_channel_points_automatic_reward_redemption_add.cpp',
  'events/channel_channel_points_custom_reward_add.cpp',
  'events/channel_channel_points_custom_reward_redemption_add.cpp',
  'events/channel_channel_points_custom_reward_redemption_update.cpp',
  'events/channel_channel_points_custom_reward_remove.cpp',
  'events/channel_channel_points_custom_reward_update.cpp',
  'events/channel_charity_campaign_donate.cpp',
  'events/channel_charity_campaign_progress.cpp',
  'events/channel_charity_campaign_start.cpp',
  'events/channel_charity_campaign_stop.cpp',
  'events/channel_chat_clear.cpp',
  'events/channel_chat_clear_user_messages.cpp',
  'events/channel_chat_message.cpp',
  'events/channel_chat_message_delete.cpp',
  'events/channel_chat_notification.cpp',
  'events/channel_chat_settings_update.cpp',
  'events/channel_chat_user_message_hold.cpp',
  'events/channel_chat_user_message_update.cpp',
  'events/channel_cheer.cpp',
  'events/channel_follow.cpp',
  'events/channel_goal_begin.cpp',
  'events/channel_goal_end.cpp',
  'events/channel_goal_progress.cpp',
  'events/channel_guest_star_guest_update.cpp',
  'events/channel_guest_star_session_begin.cpp',
  'events/channel_guest_star_session_end.cpp',
  'events/channel_guest_star_settings_update.cpp',
  'events/channel_hype_train_begin.cpp',
  'events/channel_hype_train_end.cpp',
  'events/channel_hype_train_progress.cpp',
  'events/channel_moderate.cpp',
  'events/channel_moderator_add.cpp',
  'events/channel_moderator_remove.cpp',
  'events/channel_poll_begin.cpp',
  'events/channel_poll_end.cpp',
  'events/channel_poll_progress.cpp',
  'events/channel_prediction_begin.cpp',
  'events/channel_prediction_end.cpp',
  'events/channel_prediction_lock.cpp',
  'events/channel_prediction_progress.cpp',
  'events/channel_raid.cpp',
  'events/channel_shared_chat_begin.cpp',
  'events/channel_shared_chat_end.cpp',
  'events/channel_shared_chat_update.cpp',
  'events/channel_shield_mode_begin.cpp',
  'events/channel_shield_mode_end.cpp',
  'events/channel_shoutout_create.cpp',
  'events/channel_shoutout_receive.cpp',
  'events/channel_subscribe.cpp',
  'events/channel_subscription_end.cpp',
  'events/channel_subscription_gift.cpp',
  'events/channel_subscription_message.cpp',
  'events/channel_suspicious_user_message.cpp',
  'events/channel_suspicious_user_update.cpp',
  'events/channel_unban.cpp',
  'events/channel_unban_request_create.cpp',
  'events/channel_unban_request_resolve.cpp',
  'events/channel_update.cpp',
  'events/channel_vip_add.cpp',
  'events/channel_vip_remove.cpp',
  'events/channel_warning_acknowledge.cpp',
  'events/channel_warning_send.cpp',
  'events/conduit_shard_disabled.cpp',
  'events/drop_entitlement_grant.cpp',
  'events/extension_bits_transaction_create.cpp',
  'events/stream_offline.cpp',
  'events/stream_online.cpp',
  'events/user_authorization_grant.cpp',
  'events/user_authorization_revoke.cpp',
  'events/user_update.cpp',
  'events/user_whisper_message.cpp',
  'eventsub_client.cpp',
  'http_server.cpp',
  'http_server_request.cpp',
  'https_client.cpp',
  'hype_train.cpp',
  'message.cpp',
  'moderate.cpp',
  'poll.cpp',
  'prediction.cpp',
  'scope.cpp',
  'socket.cpp',
  'socketengine.cpp',
  'socketengine_poll.cpp',
  'ssl_connection.cpp',
  'ssl_context.cpp',
  'timer.cpp',
  'user.cpp',
  'utility.cpp',
  'websocket.cpp'
)

cpp_args = [ '-DTPP_BUILD' ]

if static_build
  cpp_args += [ '-DTPP_STATIC' ]
endif

libtpp = library(
  'tpp',
  libtpp_sources,
  include_directories : private_headers + public_headers,
  dependencies : deps,
  install : true,
  version : meson.project_version(),
  cpp_args : cpp_args
)

libtpp_dep = declare_dependency(
  include_directories : public_headers,
  link_with : libtpp,
  dependencies : deps,
)
